dist: trusty
language: cpp

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq lcov curl libboost-filesystem-dev libboost-system-dev libboost-thread-dev libboost-program-options-dev libboost-test-dev ocl-icd-opencl-dev opencl-headers libnetcdf-dev libhwloc-dev libltdl-dev pkg-config libedit-dev
  - wget https://github.com/pocl/pocl/archive/v1.0.tar.gz
  - tar xzf pocl-1.0.tar.gz && cd pocl-1.0
  - cmake .
  - make -j2 && sudo make install
  - cd ..

script:
  - mkdir build
  - cd build
  - export COVERALLS_SERVICE_NAME=travis-ci
  - export COVERALLS_REPO_TOKEN=N5DQzXpRwmJg84M0xfeFlDV2D6Zz4yUVt
  - cmake -DCOVERALLS=ON -DCMAKE_BUILD_TYPE=Debug ..
  - make
  - export KERNELDIR=../../sim/src/kernels/
  - make coveralls
